### ISSUE TITLE
NoSuchMethodError: java.lang.String.isBlank()Z

### ISSUE THREAD

**Issue by jshea** [cdimascio/dotenv-java#17]
My .env contains
```
GOOD_BOY=Fluffy
NOT_SO_GOOD=Killer
```

I'm accessing it with
```java
public class KeyLoaderListener implements ServletContextListener {
   private ServletContext context = null;
   private Dotenv dotenv;

   public KeyLoaderListener() {
      this.dotenv = Dotenv.load();   // Line 30 where error occurs
   }
   ...
}
```

And getting this error
```java
java.lang.NoSuchMethodError: java.lang.String.isBlank()Z
at io.github.cdimascio.dotenv.internal.DotenvParser.parse(DotenvParser.java:33)
at io.github.cdimascio.dotenv.DotenvBuilder.load(DotenvBuilder.java:81)
at io.github.cdimascio.dotenv.Dotenv.load(Dotenv.java:33)
at com.mytest.KeyLoaderListener.<init>(KeyLoaderListener.java:30)
```

**Comment by cdimascio** [comment]
@jshea thanks for the issue. this is resolve in `v2.2.0`

**Comment by cdimascio** [comment]
the `v2.2.o` version is now live on jcenter. it should propagate to mavencentral soon.
