### ISSUE TITLE
java.lang.NoClassDefFoundError: io/github/cdimascio/dotenv/Dotenv

### ISSUE THREAD

**Issue by cooffeeRequired** [cdimascio/dotenv-java#45]
[01:25:02 ERROR]: Error occurred while enabling SkJson v1.0-SNAPSHOT (Is it up to date?)
java.lang.NoClassDefFoundError: io/github/cdimascio/dotenv/Dotenv
        at cz.coffee.SkJson.onEnable(SkJson.java:125) ~[skJson-legacy-1.0-SNAPSHOT-all.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:372) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:550) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:624) ~[purpur-1.19.3.jar:git-Purpur-1864]
        
I got everything right, but this is still happening.
```gradle
dependencies {
    compileOnly 'com.destroystokyo.paper:paper-api:1.16.5-R0.1-SNAPSHOT'
    compileOnly 'org.projectlombok:lombok:1.18.24'
    compileOnly 'org.jetbrains:annotations:23.1.0'
    compileOnly 'com.github.SkriptLang:Skript:2.6.3'

    implementation group: 'org.eclipse.jdt', name: 'org.eclipse.jdt.annotation', version: '2.2.700'
    implementation group: 'org.yaml', name: 'snakeyaml', version: '1.33'
    implementation("io.github.cdimascio:dotenv-java:2.3.1")

    //testImplementation(shadow('com.google.code.gson:gson:2.10'))
    //testImplementation('com.destroystokyo.paper:paper-api:1.16.5-R0.1-SNAPSHOT')

    shadow('com.google.code.gson:gson:2.10')
}
```

**Comment by cdimascio** [comment]
Please try the latest 

```
implementation 'io.github.cdimascio:dotenv-java:2.3.2'
```
