### ISSUE TITLE
Could not find ./.env on the file system (working directory:/)

### ISSUE THREAD

**Issue by Satyam-953** [cdimascio/dotenv-java#56]
Hi readers

I am setting up this package in my java project, have added dependency and also created a .env file
but when calling configure() as mentioned below

`
        Dotenv dotenv = Dotenv
                .configure()
                .load();`

`	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2574)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:226)
                                                                                                    	at android.os.Looper.loop(Looper.java:313)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8757)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
                                                                                                    Caused by: io.github.cdimascio.dotenv.DotenvException: Could not find /.env on the classpath
                                                                                                    	at io.github.cdimascio.dotenv.internal.ClasspathHelper.loadFileFromClasspath(ClasspathHelper.java:25)
                                                                                                    	at io.github.cdimascio.dotenv.internal.DotenvReader.read(DotenvReader.java:55)
                                                                                                    	at io.github.cdimascio.dotenv.internal.DotenvParser.lines(DotenvParser.java:87)
                                                                                                    	at io.github.cdimascio.dotenv.internal.DotenvParser.parse(DotenvParser.java:60)
                                                                                                    	at io.github.cdimascio.dotenv.DotenvBuilder.load(DotenvBuilder.java:76) 
at com.example.activity.splash.onCreate(Splash.java:33)
	at android.app.Activity.performCreate(Activity.java:8591)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8570)
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1384)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4150)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4325) 
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2574) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:226) 
                                                                                                    	at android.os.Looper.loop(Looper.java:313) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8757) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067) 
                                                                                                    	Suppressed: io.github.cdimascio.dotenv.DotenvException: Could not find ./.env on the file system (working directory: /)
                                                                                                    		at io.github.cdimascio.dotenv.internal.DotenvReader.read(DotenvReader.java:60)
`

I ended up pasting .env file on every root of the project for example project/app/ , project/ ,  project/app/src  ... but nun of that worked. !

**Comment by neilfranci** [comment]
Did you find any hope?
Or is this broken?

My Project Structure:
![image](https://github.com/user-attachments/assets/b2c39e74-6def-41c6-a0f0-ee09825b14ff)

@cdimascio

**Comment by cdimascio** [comment]
Have a look at the android usage section here
https://github.com/cdimascio/dotenv-kotlin?tab=readme-ov-file#android-usage

Note the use of env not .env

**Comment by neilfranci** [comment]
> Have a look at the android usage section here https://github.com/cdimascio/dotenv-kotlin?tab=readme-ov-file#android-usage
> 
> Note the use of env not .env

I make a mistake. I thought this was on PC but it's mobile. But still, I'm trying to get it working with spring-boot and graalvm
two different types and it just doesn't work well together. 
```mvn -pl server spring-boot:run```
and
```mvn -pl server -Pnative native:compile```
