### ISSUE TITLE
StringIndexOutOfBoundsException for broken .env file while using ignoreIfMalformed

### ISSUE THREAD

**Issue by panzi** [cdimascio/dotenv-java#63]
I use this deliberately really broken `.env` file to test stuff, and dotenv-java crashes with an StringIndexOutOfBoundsException on it. Is the `ignoreIfMalformed` option supposed to catch these or is this out of scope for this library?

```dotenv
FOO="
```

The problem is that `isQuoted()` checks if the value starts and ends with `"`, but not that it is longer than a single character, and later `normalizeValue()` tries to slice of a character from the start and end.

Backtrace:
```
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: begin 1, end 0, length 1
        at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4601)
        at java.base/java.lang.String.substring(String.java:2704)
        at io.github.cdimascio.dotenv.internal.DotenvParser.normalizeValue(DotenvParser.java:99)
        at io.github.cdimascio.dotenv.internal.DotenvParser.addNewEntry(DotenvParser.java:81)
        at io.github.cdimascio.dotenv.internal.DotenvParser.parse(DotenvParser.java:63)
        at io.github.cdimascio.dotenv.DotenvBuilder.load(DotenvBuilder.java:76)
        at dotenv.Main.main(Main.java:31)
```

**Comment by cdimascio** [comment]
would you be interested in posting a PR?

**Comment by panzi** [comment]
You could just change `isQuoted` to:
```Java
private final Predicate<String> isQuoted = s -> s.length() > 1 && s.startsWith("\"") && s.endsWith("\"");
```

Or change `normalizeValue()` to:
```Java
    private String normalizeValue(final String value) {
        final var tr = value.trim();
        if (isQuoted.test(tr)) {
            return tr.length() > 1 ? tr.substring(1, tr.length() - 1) : "";
        }
        return tr;
    }
```

(I just noticed that `normalizeValue()` has another bug where it used `value` where it should use `tr`.)

Or change the last line of `addNewEntry()` to:

```Java
if (value.equals("\"")) {
    if (throwIfMalformed)
        throw new DotenvException("Malformed entry " + line);
    return;
}
entries.add(new DotenvEntry(key, value));
```

Depending on what you think should happen. I just think there shouldn't an exception be thrown when `throwIfMalformed` is `false`.
